services:
  nginx:
    image: nginx:alpine
    container_name: hive_nginx_prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl  # Mount SSL certificates here
    depends_on:
      - frontend
      - backend
    networks:
      - hive_network_prod

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/api
        - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
    container_name: hive_frontend_prod
    restart: always
    expose:
      - "80"
    networks:
      - hive_network_prod

  backend:
    build: ./backend
    container_name: hive_backend_prod
    restart: always
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DEPLOY_TYPE=prod
      - FRONTEND_URL=${FRONTEND_URL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - RUN_SEED_OFFERS=${RUN_SEED_OFFERS}
    networks:
      - hive_network_prod

  postgres:
    image: postgres:16-alpine
    container_name: hive_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    volumes:
      - postgres_data_hive_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hive_network_prod

networks:
  hive_network_prod:
    driver: bridge

volumes:
  postgres_data_hive_prod:
    driver: local
